---
title: "Benchmark"
author: "Marcelo Hurtado"
date: "2025-06-16"
output: html_document
---

Load libraries
```{r}
library(Decosus)
library(dplyr)
library(multideconv)
```

Load pseudobulk
```{r}
pseudobulk = read.csv("../output/Pseudobulk_sc.csv", row.names = 1, sep = "\t")
```

Deconvolution multideconv pseudobulk
```{r}
deconv_multideconv = read.csv("../output/Deconvolution_Pseudobulk.csv", row.names = 1)
deconv_multideconv = deconv_multideconv[,-grep("Vanderbilt", colnames(deconv_multideconv))]
deconv_subgroups = multideconv::compute.deconvolution.analysis(deconv_multideconv, cells_extra = c("Mural.cells", "Myeloid.cells", "T.cells.proliferative", "Plasma"))
colnames(deconv_subgroups[[1]]) = paste0("multideconv_", colnames(deconv_subgroups[[1]]))
```

Consensus TME
```{r}
deconv_consensus = t(immunedeconv::deconvolute_consensus_tme(pseudobulk, indications = rep('luad', ncol(pseudobulk))))
colnames(deconv_consensus) = stringr::str_replace(colnames(deconv_consensus), "B_cells", "B.cells")
colnames(deconv_consensus) = stringr::str_replace(colnames(deconv_consensus), "Mast_cells", "Mast.cells")
colnames(deconv_consensus) = stringr::str_replace(colnames(deconv_consensus), "NK_cells", "NK.cells")
colnames(deconv_consensus) = stringr::str_replace(colnames(deconv_consensus), "T_cells_CD4", "CD4.cells")
colnames(deconv_consensus) = stringr::str_replace(colnames(deconv_consensus), "T_cells_CD8", "CD8.cells")
colnames(deconv_consensus) = stringr::str_replace(colnames(deconv_consensus), "T_regulatory_cells", "T.cells.regulatory")
colnames(deconv_consensus) = stringr::str_replace(colnames(deconv_consensus), "Plasma_cells", "Plasma")
colnames(deconv_consensus) = paste0("Consensus_", colnames(deconv_consensus))
```

Decosus
```{r}
deconv_decosus <- t(Decosus::cosDeco(x=pseudobulk %>% tibble::rownames_to_column("gene"))$main_samples)
colnames(deconv_decosus) <- stringr::str_replace_all(colnames(deconv_decosus), " ", ".")
colnames(deconv_decosus) <- stringr::str_replace_all(colnames(deconv_decosus), "Endothelial\\.cell_consensus", "Endothelial")
colnames(deconv_decosus) <- stringr::str_replace_all(colnames(deconv_decosus), "Mast\\.cell_consensus", "Mast.cells")
colnames(deconv_decosus) <- stringr::str_replace_all(colnames(deconv_decosus), "B\\.cell_consensus", "B.cells")
colnames(deconv_decosus) <- stringr::str_replace_all(colnames(deconv_decosus), "NK\\.cell_consensus", "NK.cells")
colnames(deconv_decosus) <- stringr::str_replace_all(colnames(deconv_decosus), "T\\.cell\\.CD8\\+_consensus", "CD8.cells")
colnames(deconv_decosus) <- stringr::str_replace_all(colnames(deconv_decosus), "T\\.cell\\.regulatory\\.\\(Tregs\\)_consensus", "T.cells.regulatory")
colnames(deconv_decosus) <- stringr::str_replace_all(colnames(deconv_decosus), "Cancer\\.associated\\.fibroblast_consensus", "CAF")
colnames(deconv_decosus) <- stringr::str_replace_all(colnames(deconv_decosus), "Macrophage\\_consensus", "Macrophages.cells")
colnames(deconv_decosus) <- stringr::str_replace_all(colnames(deconv_decosus), "Monocyte\\_consensus", "Monocytes")
colnames(deconv_decosus) <- stringr::str_replace_all(colnames(deconv_decosus), "Neutrophil\\_consensus", "Neutrophils")
colnames(deconv_decosus) <- stringr::str_replace_all(colnames(deconv_decosus), "Myeloid\\.dendritic\\.cell_consensus", "Dendritic.cells")
colnames(deconv_decosus) = paste0("Decosus_", colnames(deconv_decosus))
```

Benchmarking deconvolution

Groundtruth
```{r}
cells_groundtruth = read.csv("../output/Cells_groundtruth_Vanderbilt.csv", row.names = 1)
```

Benchmark 
```{r}
data = cbind(deconv_subgroups[[1]], deconv_consensus, deconv_decosus)
corr_matrix = compute.benchmark(data, cells_groundtruth, include_combinations = c("multideconv", "Decosus", "Consensus"),
                                         corr_type = "pearson", scatter = F, pval = 0.05, file_name = "Vanderbilt_benchmark", height = 5, width = 10)
```

Benchmark subgroups performance
```{r}
source("benchmark_function.R")
source("~/Documents/multideconv/R/cell_deconvolution.R")
deconv_1 = deconv_subgroups[[1]][,-grep("Subgroup", colnames(deconv_subgroups[[1]]))]
deconv_sub = deconv_subgroups[[1]][,grep("Subgroup", colnames(deconv_subgroups[[1]]))]

corr_matrix_deconv = compute.benchmark(deconv_1, cells_groundtruth, 
                                corr_type = "pearson", scatter = F, pval = 0.05, file_name = "Vanderbilt_Subgroups")
corr_matrix_subgroups = benchmarking_deconvolution(deconv_sub, cells_groundtruth, 
                                                   include_combinations = c("Subgroup.1.Iteration.1", "Subgroup.1.Iteration.2",
                                                                            "Subgroup.2.Iteration.1",                                                     
                                                                            "Subgroup.3.Iteration.1", "Subgroup.4.Iteration.1"),
                                corr_type = "pearson", scatter = F, pval = 0.05, file_name = "Vanderbilt_Subgroups")

corr_matrix_deconv = corr_matrix_deconv[rownames(corr_matrix_deconv)%in%rownames(corr_matrix_subgroups),]
corr_matrix_subgroups = corr_matrix_subgroups[rownames(corr_matrix_subgroups)%in%rownames(corr_matrix_deconv),]

corr_all = cbind(corr_matrix_deconv, corr_matrix_subgroups)

corr_df <- melt(corr_all)
corr_df = corr_df %>%
  mutate(Cells = rep(rownames(corr_all), ncol(corr_all)))

g <- corr_df %>%
  dplyr::filter(Cells != "average") %>%
  ggplot(aes(Cells, variable, fill=value, label=round(value,2))) +
  geom_tile() +
  labs(x = NULL, y = NULL, fill = paste0(corr_type, "'s\nCorrelation"), title="Vanderbilt - multideconv subgroups") +
  scale_fill_gradient2(mid="#FBFEF9",low="#0C6291",high="#A63446", limits=c(-1,1)) +
  geom_text() +
  theme_classic() +
  scale_x_discrete(expand=c(0,0)) +
  scale_y_discrete(expand=c(0,0)) +
  ggpubr::rotate_x_text(angle = 45) + theme(axis.text.x=ggtext::element_markdown()) + theme(axis.text.y=ggtext::element_markdown())

pdf("Benchmark_plot_subgroups", width = 10, height = 8)
print(g)
dev.off()
```

