---
title: "Benchmark"
author: "Marcelo Hurtado"
date: "2025-06-16"
output: html_document
---

Load input
```{r}
counts = read.delim("../input/Gide_log2TPM.txt", row.names = 1)
coldata = read.csv("../input/Clinical_Gide.csv", row.names = 1)
```

Consensus TME
```{r}
deconv_consensus = t(immunedeconv::deconvolute_consensus_tme(counts, indications = rep('skcm', ncol(counts))))
rownames(deconv_consensus) = stringr::str_replace(rownames(deconv_consensus), "X", "")
```

Load deconv subgroups
```{r}
load("../output/Subgroups_Gide.RData")
```

ML analysis
```{r}
library(pipeML)
library(caret)
features = cbind(subgroups$`Deconvolution matrix`, deconv_consensus)
res_ml = compute_features.training.ML(features, coldata$Response, "R", 
                                      metric = "AUROC", stack = F, k_folds = 5, 
                                      n_rep = 20, feature.selection = F, seed = 123, 
                                      file_name = "Gide_consensusTME", ncores = 2, return = T)
```

Variable importance
```{r}
importance_subgroups = pipeML::compute_variable.importance(res_ml, stacking = F, n_cores = 2)
plot_shap_values(importance_subgroups, "GLM", file_name = "Var_importance")
```

