---
title: "Deconvolution_dictionary"
author: "Marcelo Hurtado"
date: "2025-11-18"
output: html_document
---

Load library
```{r}
library(multideconv)
```

Load deconvolution input
```{r}
load("../output/Subgroups_Gide.RData")
counts.norm = read.delim("../input/Gide_log2TPM.txt", row.names = 1)
colnames(counts.norm) = stringr::str_replace(colnames(counts.norm), "X", "")
deconv = read.csv("../output/Deconvolution_Gide.csv", row.names = 1)
rownames(deconv) = stringr::str_replace(rownames(deconv), "X", "")
```

Apply subgroupping and dictionary
```{r}
pathways = CellTFusion::compute.pathway.activity(counts.norm)[[1]]
deconv_subgroups_dict = deconvolution_dictionary(subgroups, pathways)
```

Heatmap macrophages
```{r}
celltype = "Monocytes"
library(ComplexHeatmap)
cells = subgroups$`Deconvolution subgroups per cell types`[[celltype]]
ht1 = ComplexHeatmap::Heatmap(t(scale(cells)), 
        border = T, column_gap = unit(8, "mm"), 
        name = "Deconvolution", clustering_method_rows = "ward.D2", 
        column_dend_height = unit(5, "cm"), row_dend_width = unit(5, "cm"), 
        column_dend_reorder = T, row_dend_reorder = F,
        show_row_names = T, show_column_names = F,
        show_heatmap_legend = T, 
        row_names_gp = gpar(fontsize = 8), 
        column_names_gp = gpar(fontsize =8), 
        width = unit(8, "cm"), height = unit(5, "cm"),
        heatmap_legend_param = list(labels_gp = gpar(fontsize = 12), legend_width = unit(12, "cm"), 
                                    legend_heigh = unit(12, "cm"), title_gp = gpar(fontsize = 12)))
draw(ht1, show_heatmap_legend = T, heatmap_legend_side = "left", annotation_legend_side = 'left')

#Pathways - cells
CellTFusion::compute.modules.relationship(cells, pathways,file_name = celltype, height = 6, width = 12, par_mar = c(4, 25, 5, 3), pval = 0.05)
```

Subgroups composition
```{r}
cat("Composition Monocytes_Subgroup.1.Iteration.2: \n")
subgroups[["Deconvolution subgroups composition"]][["Monocytes"]][["Monocytes_Subgroup.1.Iteration.2"]]
subgroups[["Deconvolution subgroups composition"]][["Monocytes"]][["Monocytes_Subgroup.4.Iteration.1"]]
cat("Composition Monocytes_Subgroup.2.Iteration.1: \n")
subgroups[["Deconvolution subgroups composition"]][["Monocytes"]][["Monocytes_Subgroup.2.Iteration.1"]]
```

