---
title: "Machine learning models"
author: "Marcelo Hurtado"
date: "2025-04-24"
output: html_document
---

Set up environment
```{r setup, include=FALSE}
require(multideconv)
require(dplyr)
require(tictoc)
require(pipeML)
require(caret)
set.seed(123) #For reproducibility
```

Load input
```{r}
counts = read.delim("../input/Gide_log2TPM.txt", row.names = 1)
coldata = read.csv("../input/Clinical_Gide.csv", row.names = 1)
```

Deconvolution
```{r}
# deconv = compute.deconvolution(counts, normalized = F, credentials.mail = "marcelo.hurtado@inserm.fr", doParallel = T, workers = 3,
#                                credentials.token = "734212f6ad77fc4eea2bdb502792f294", file_name = "Gide")
deconv = read.csv("../output/Deconvolution_Gide.csv", row.names = 1)
rownames(deconv) = stringr::str_replace(rownames(deconv), "X", "")
#Subgroups
#subgroups = compute.deconvolution.analysis(deconvolution = deconv, corr = 0.7, seed = 123, file_name = "Gide") 
load("../output/Subgroups_Gide.RData")
#Remove high zero columns
deconv = deconv[, colSums(deconv == 0, na.rm=TRUE) < round(0.9*nrow(deconv)) , drop=FALSE]
#Remove low variance features
vars <- apply(deconv, 2, var)
low_variance <- which(vars < summary(vars)[[2]])
deconv = deconv[,-low_variance, drop = F]
```

ML training
```{r}
tictoc::tic() #928.458
res_deconv <- compute_features.training.ML(features_train = deconv, 
                                          target_var = coldata$Response,
                                          task_type = "classification",
                                          trait.positive = "R",
                                          metric = "AUROC",
                                          stack = FALSE,
                                          k_folds = 5,
                                          n_rep = 20,
                                          LODO = FALSE,
                                          batch_id = NULL,
                                          file_name = "Gide_deconv_raw",
                                          ncores = 4,
                                          return = FALSE)
tictoc::toc()
save(res_deconv, file = "ML_models_Gide_raw_deconv.RData")

tictoc::tic() #883.211
res_subgroups <- compute_features.training.ML(features_train = subgroups[[1]], 
                                              target_var = coldata$Response,
                                              task_type = "classification",
                                              trait.positive = "R",
                                              metric = "AUROC",
                                              stack = FALSE,
                                              k_folds = 5,
                                              n_rep = 20,
                                              LODO = FALSE,
                                              batch_id = NULL,
                                              file_name = "Gide_deconv_subgroups",
                                              ncores = 4,
                                              return = FALSE)
tictoc::toc()
save(res_subgroups, file = "ML_models_Gide_subgroups_deconv.RData")
```

Compute variable importance
```{r}
tic() #304.987 
importance_subgroups = compute_variable.importance(res_subgroups, stacking = F, n_cores = 2)
toc()
save(importance_subgroups, file = "SHAP_importance_Gide_subgroups_deconv.RData")

tic() #5010.063
importance_deconv = compute_variable.importance(res_deconv, stacking = F, n_cores = 2)
toc()
save(importance_deconv, file = "SHAP_importance_Gide_raw_deconv.RData")

pipeML::plot_shap_values(importance_subgroups, res_subgroups$Model$method, file_name = "SHAP_importance_Gide_subgroups_deconv")
pipeML::plot_shap_values(importance_deconv, res_deconv$Model$method, file_name = "SHAP_importance_Gide_raw_deconv")
```

Plots CV metrics
```{r}
compute_models_metric = function(models, cohort_name){
  auroc = list()
  for (i in 1:length(models)){
    auroc[[i]] = models[[i]]$resample %>% 
      mutate(model = names(models)[i])
    names(auroc)[i] = names(models)[i]
  }
  auroc_data = do.call(rbind, auroc)

  res_auroc <- auroc_data %>%
    group_by(model) %>%
    summarise(
      Mean_AUROC = median(AUROC),
      SD_AUROC = sd(AUROC)
    ) %>%
    arrange(desc(Mean_AUROC)) %>%
    mutate(Method = cohort_name)
}

metrics_raw = compute_models_metric(res_deconv$ML_Models, "Raw_deconvolution")
metrics_subgroups = compute_models_metric(res_subgroups$ML_Models, "Subgroups_deconvolution")
metrics_all = rbind(metrics_raw, metrics_subgroups)

pdf("Results/AUROC_CV_methods.pdf", width = 10)
plot(ggplot(metrics_all, aes(x = model, y = Mean_AUROC, fill = Method)) +
       geom_bar(stat = "identity", position = position_dodge(), width = 0.6) + 
       geom_errorbar(aes(ymin = Mean_AUROC - SD_AUROC, ymax = Mean_AUROC + SD_AUROC),
                     width = 0.2, position = position_dodge(0.6)) +
       labs(title = "Performance of Models",
            x = "Model",
            y = "Median AUROC") +
       theme_minimal() +
       theme(axis.text.x = element_text(angle = 45, hjust = 1),
             legend.position = "right") +
       scale_y_continuous(breaks = seq(0, 1, by = 0.05))) 
dev.off()
```

